### ISSUE TITLE
Missing support for ES5 compiled apps

### ISSUE THREAD

**Issue by duckyb** [Trott/node-slug#18]
Me and my team are trying to support IE11 in our Angular 8 application, but unfortunately this library breaks vendor.js because of the arrow function syntax.

## Screenshot of the problem
![img](https://i.imgur.com/wNYqcJq.png)

## Minimal reproduction App
[slug-error-minimal.zip](https://github.com/Trott/node-slug/files/4111912/slug-error-minimal.zip)

Running the reproduction:
1. Unzip
2. run `npm i`
3. run `ng serve`
4. open IE11

A fix for this would be greatly appreciated!

**Comment by Trott** [comment]
Fixed in #19
