### ISSUE TITLE
Simple algorithm to detect ambiguous situations

### ISSUE THREAD

**Issue by Trott** [Trott/node-slug#44]
It seems that the character `đ` may be transliterated in at least three different ways:

* `dj` in Serbian according to https://en.wikipedia.org/wiki/D_with_stroke and https://github.com/django/django/blob/master/django/contrib/admin/static/admin/js/urlify.js
* `gj` in Macedonian according to https://en.wikipedia.org/wiki/D_with_stroke 
* `d` in Vietnamese (according to https://github.com/simov/slugify/issues/49). 

Perhaps the algorithm for this (and other characters that can be transliterated in multiple ways) might be:

* If the input string contains no ambiguous characters (such as `đ`), use the current algorithm.
* Otherwise, we need to figure out the language, Naive first-pass implementation will be:
  * If the input string consists entirely of characters that are valid in one of the languages but not any of the others, use that language's transliteration.
  * Otherwise, take the list of possible languages (that is, languages for which all characters in the string are valid), and select the language with the most native speakers. (I believe in this case, the ordering would be Vietnamese, Serbian, Macedonian.) That will at least hopefully tend to guess correctly.
  * If there are no languages that can contain all the characters, use the transliteration from the language with the most native speakers (in this case, Vietnamese).

This can be iterated on to improve it, but something simple like this is probably better than what we have now (which is "we have Serbian, so that's what we're using"). And we probably don't need to go full machine-learning model on this.

**Comment by Trott** [comment]
I tried this and it's more complicated and less reliable than this suggests. I think it's best for now for the user to simply provide an override replacement string for the language they care about.

**Comment by simov** [comment]
Yep, I have a `locale` option in the works, but it's not officially documented yet.

You can see it in the main file that I have:

```js
var locales = JSON.parse('{"vi":{"Đ":"D","đ":"d"}}')
```

The idea was that the most efficient way in terms of bundle size was to have all possible characters in the main charmap, as they were added over time without regard to a specific locale, and then override only the necessary characters in locale specific JSON. The reason why is because many locales can have overlaps in the way they translate certain character, which is good.

**Comment by simov** [comment]
Oh, wait, I just commented in your repo .. I was redirected from mine .. anyway

**Comment by Trott** [comment]
Yeah, I implemented the same thing because of the issue with Vietnamese vs. Serbian, and also because Bulgarian is transliterated different from other languages with which it shares characters.

```javascript
  const locales = {
    // http://www.eki.ee/wgrs/rom1_bg.pdf
    bg: { Й: 'Y', й: 'y', X: 'H', x: 'h', Ц: 'Ts', ц: 'ts', Щ: 'Sht', щ: 'sht', Ъ: 'A', ъ: 'a', Ь: 'Y', ь: 'y' },
    // Need a reference URL for Serbian.
    sr: { đ: 'dj', Đ: 'DJ' }
  }
```

I see you default to Serbian and allow a Vietnamese locale. I did the opposite on the grounds that far more people speak Vietnamese than Serbian. Wasn't really sure of another "fair" way to decide which should be the default. I guess you went with Serbian because it was already there in the code so it became the default?

**Comment by simov** [comment]
Yes, stuff got added over time, then people started submitting PRs about the 'correct' way to translate a character according to language X, and so that's how I ended up having locales. Though I should document that, so people can have a way to resolve those kind of issues.

**Comment by Trott** [comment]
Heh, now that you mention it, I didn't document it either other than including an example using `locale`. But it's not listed in the options or anything. Whoops!
